[package]
name = "solanum"
version = "3.0.1"
edition = "2021"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.3.0"
glib-macros = "0.17"
gstreamer = "0.20"
gstreamer-player = "0.20"
libadwaita = { version = "0.3.0", features = ["v1_2"] }

[dependencies.gtk]
version = "0.6"
package ="gtk4"

[dependencies.gdk]
version = "0.6"
package = "gdk4"

[dependencies.gio]
version = "0.17"
features = ["v2_60"]

[dependencies.glib]
version = "0.17"
features = ["v2_60"]

[dependencies.gettext-rs]
version = "0.7.0"
features = ["gettext-system"]

[dependencies.pango]
version = "0.17"
features = ["v1_44"]
