[package]
name = "solanum"
version = "2.0.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.2.0"
field-offset = "0.3.2"

[dependencies.gtk4]
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "gobject-sys"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "glib-sys"

[dependencies.gdk4]
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_60"]

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_60"]

[dependencies.gstreamer]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-player]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gettext-rs]
version = "0.4.4"
features = ["gettext-system"]

[dependencies.libhandy]
git = "https://gitlab.gnome.org/bilelmoussaoui/libhandy4-rs"
package = "libhandy4"

[dependencies.pango]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v1_44"]
