[package]
name = "solanum"
version = "2.0.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.2.0"
gstreamer = "0.16.3"
gstreamer-player = "0.16.3"

[dependencies.gtk4]
git = "https://github.com/gtk-rs/gtk4"

[dependencies.gdk4]
git = "https://github.com/gtk-rs/gdk4"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
features = ["v2_60"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
features = ["v2_60"]

[dependencies.gettext-rs]
version = "0.4.4"
features = ["gettext-system"]

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"
features = ["v1_44"]
