[package]
name = "solanum"
version = "2.0.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.2.0"
gstreamer = "0.17"
gstreamer-player = "0.17"
libadwaita = "0.1.0-alpha-6"

[dependencies.gtk]
version = "0.3"
package ="gtk4"

[dependencies.gdk]
version = "0.3"
package = "gdk4"

[dependencies.gio]
version = "0.14"
features = ["v2_60"]

[dependencies.glib]
version = "0.14"
features = ["v2_60"]

[dependencies.gettext-rs]
version = "0.4.4"
features = ["gettext-system"]

[dependencies.pango]
version = "0.14"
features = ["v1_44"]
