[package]
name = "solanum"
version = "2.0.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.2.0"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4-rs"
package ="gtk4"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gdk4"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs-core"
features = ["v2_60"]

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs-core"
features = ["v2_60"]

[dependencies.gstreamer]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gstreamer-player]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"

[dependencies.gettext-rs]
version = "0.4.4"
features = ["gettext-system"]

[dependencies.libadwaita]
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs"

[dependencies.pango]
git = "https://github.com/gtk-rs/gtk-rs-core"
features = ["v1_44"]
