[package]
name = "solanum"
version = "1.0.0"
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.4"
gtk-macros = "0.2.0"
libhandy = "0.7.0"
gstreamer = "0.16.3"
gstreamer-player = "0.16.3"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_24"]

[dependencies.gdk]
version = "0.13.0"
features = ["v3_24"]

[dependencies.gio]
version = "0.9.0"
features = ["v2_60"]

[dependencies.glib]
version = "0.10.0"
features = ["v2_60"]

[dependencies.gettext-rs]
version = "0.4.4"
features = ["gettext-system"]

[dependencies.pango]
version = "0.9.1"
features = ["v1_44"]
